### ISSUE TITLE
Errors: Cant find channels

### ISSUE THREAD

**Issue by Chris230291** [fHDHR/fHDHR#130]
I have fHDHR inside a custom docker container that has TVH and PlutoTV enabled...

```
FROM python:3.8-slim

RUN apt-get -qq update && \
    apt-get -qq -y install ffmpeg gcc git && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN git clone https://github.com/fHDHR/fHDHR.git .
RUN pip3 install -r requirements.txt

WORKDIR /app/plugins

RUN git clone https://github.com/fHDHR/fHDHR_plugin_origin_tvheadend.git
RUN git clone https://github.com/fHDHR/fHDHR_plugin_origin_plutotv.git
#RUN git clone https://github.com/fHDHR/fHDHR_plugin_origin_XUMO.git
#RUN git clone https://github.com/fHDHR/fHDHR_plugin_origin_STIRR.git
#RUN git clone https://github.com/fHDHR/fHDHR_plugin_origin_locast.git

RUN for req in ./*/requirements.txt; do pip3 install -r $req; done

ENTRYPOINT ["python3", "/app/main.py", "--config", "/app/config/config.ini"]
```

The container starts up and I can access the web UI.
Searching for channels gives the following errors...

```
[2021-02-24 16:12:04,893] NOOB - Performing Channel Scan for plutotv. This Process can take some time, Please Wait.


Traceback (most recent call last):


  File "/app/main.py", line 16, in <module>


    sys.exit(run.main(SCRIPT_DIR, fHDHR_web))


  File "/app/fHDHR/cli/run.py", line 127, in main


    returned_code = start(args, script_dir, fHDHR_web)


  File "/app/fHDHR/cli/run.py", line 107, in start


    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler)


  File "/app/fHDHR/cli/run.py", line 41, in run


    fhdhr.api.get("/api/startup_tasks")


  File "/app/fHDHR/api/__init__.py", line 66, in get


    self.client.get(url, headers=self.headers, *args)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get


    return self.open(*args, **kw)


  File "/usr/local/lib/python3.8/site-packages/flask/testing.py", line 222, in open


    return Client.open(


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open


    response = self.run_wsgi_app(environ.copy(), buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app


    rv = run_wsgi_app(self.application, environ, buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app


    app_rv = app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__


    return self.wsgi_app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app


    response = self.handle_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app


    response = self.full_dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request


    rv = self.handle_user_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request


    rv = self.dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request


    return self.view_functions[rule.endpoint](**req.view_args)


  File "/app/fHDHR_web/api/startup_tasks.py", line 15, in __call__


    return self.get(*args)


  File "/app/fHDHR_web/api/startup_tasks.py", line 32, in get


    self.fhdhr.api.get("%s&origin=%s" % (self.channel_update_url, origin))


  File "/app/fHDHR/api/__init__.py", line 66, in get


    self.client.get(url, headers=self.headers, *args)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get


    return self.open(*args, **kw)


  File "/usr/local/lib/python3.8/site-packages/flask/testing.py", line 222, in open


    return Client.open(


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open


    response = self.run_wsgi_app(environ.copy(), buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app


    rv = run_wsgi_app(self.application, environ, buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app


    app_rv = app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__


    return self.wsgi_app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app


    response = self.handle_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app


    response = self.full_dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request


    rv = self.handle_user_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request


    rv = self.dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request


    return self.view_functions[rule.endpoint](**req.view_args)


  File "/app/fHDHR_web/api/channels.py", line 20, in __call__


    return self.get(*args)


  File "/app/fHDHR_web/api/channels.py", line 164, in get


    self.fhdhr.device.channels.get_channels(forceupdate=True, origin=origin)


  File "/app/fHDHR/device/channels/__init__.py", line 164, in get_channels


    channel_dict_list = self.origins.origins_dict[origin].get_channels()


  File "/app/plugins/fHDHR_plugin_origin_plutotv/origin/__init__.py", line 80, in get_channels


    thumbnail = channel_dict[thumb_opt]["path"].split("?")[0]


KeyError: 'logo'
```

And...

```
[2021-02-24 16:14:15,165] NOOB - Performing Channel Scan for tvheadend. This Process can take some time, Please Wait.


Exception in thread Thread-2:


Traceback (most recent call last):


  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner


    self.run()


  File "/usr/local/lib/python3.8/threading.py", line 870, in run


    self._target(*self._args, **self._kwargs)


  File "/app/fHDHR/device/tuners/tuner.py", line 45, in runscan


    self.fhdhr.api.get("%s&origin=%s" % (self.chanscan_url, origin))


  File "/app/fHDHR/api/__init__.py", line 66, in get


    self.client.get(url, headers=self.headers, *args)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get


    return self.open(*args, **kw)


  File "/usr/local/lib/python3.8/site-packages/flask/testing.py", line 222, in open


    return Client.open(


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open


    response = self.run_wsgi_app(environ.copy(), buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app


    rv = run_wsgi_app(self.application, environ, buffered=buffered)


  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app


    app_rv = app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__


    return self.wsgi_app(environ, start_response)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app


    response = self.handle_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app


    response = self.full_dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request


    rv = self.handle_user_exception(e)


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception


    reraise(exc_type, exc_value, tb)


  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise


    raise value


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request


    rv = self.dispatch_request()


  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request


    return self.view_functions[rule.endpoint](**req.view_args)


  File "/app/fHDHR_web/api/channels.py", line 20, in __call__


    return self.get(*args)


  File "/app/fHDHR_web/api/channels.py", line 164, in get


    self.fhdhr.device.channels.get_channels(forceupdate=True, origin=origin)


  File "/app/fHDHR/device/channels/__init__.py", line 164, in get_channels


    channel_dict_list = self.origins.origins_dict[origin].get_channels()


  File "/app/plugins/fHDHR_plugin_origin_tvheadend/origin/__init__.py", line 52, in get_channels


    entries = r.json()['entries']


  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json


    return complexjson.loads(self.text, **kwargs)


  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads


    return _default_decoder.decode(s)


  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode


    obj, end = self.raw_decode(s)


  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode


    return self.scan_once(s, idx=_w(s, idx).end())


simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any ideas what I am doing wrong?

Chris

**Comment by deathbybandaid** [comment]
close this, and open seperate threads for plutotv and tvheadend plugins in those repos.
