### ISSUE TITLE
connect through vpn

### ISSUE THREAD

**Issue by wbilger** [fHDHR/fHDHR#154]
is there a way to connect through a vpn such as PIA?
I use qdm12/gluetun, and it works with other containers to connect through my vpn container with;
network_mode: "service:piavpn"
But with this container I cannot, I get a bind error, address already in use.

**Comment by deathbybandaid** [comment]
What ports does glutun use?

**Comment by wbilger** [comment]
It doesn't use any as far as I understand, but can allow access to ports connected to gluten as shown here;
https://github.com/qdm12/gluetun/wiki/Connect-to-gluetun

**Comment by deathbybandaid** [comment]
Can you get me a traceback of your error from fHDHR?

**Comment by wbilger** [comment]
[2021-03-12 13:08:33,617] NOOB - Loading fHDHR v0.9.0-beta with fHDHR_web v0.9.0-beta
[2021-03-12 13:08:33,640] WARNING - Do not run fHDHR with root privileges.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/fHDHR_web/__init__.py", line 300, in run
    self.http.serve_forever()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1545, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 288, in _tcp_listener
    sock.bind(address)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 563, in bind
    return self._sock.bind(address)
OSError: [Errno 98] Address already in use: ('192.168.1.10', 5004)
[2021-03-12 13:08:37,207] NOOB - Running Startup Tasks.
[2021-03-12 13:08:37,210] NOOB - Performing Channel Scan for plutotv. This Process can take some time, Please Wait.
[2021-03-12 13:08:37,586] NOOB - Updating plutotv EPG cache.
[2021-03-12 13:08:37,815] NOOB - Wrote plutotv EPG cache. 4147 Programs for 11 Channels
[2021-03-12 13:08:37,819] NOOB - Startup Tasks Complete.

**Comment by wbilger** [comment]
Sorry, ignore that last one, as the was using network_mode: host.
If I set network_mode: "service:piavpn", fhdhr won't build.
I get this error,
ERROR: Service 'fhdhr' uses the network stack of service 'piavpn' which is undefined.
Not sure if that is an issue with docker or what, but I will dig a little further.
This is with piavpn and fhdhr in separate docker-compose.yml files, so supposed to work.

**Comment by deathbybandaid** [comment]
¯\_(ツ)_/¯

Let me know what you find.

**Comment by wbilger** [comment]
Ok, sorry again, I think I was suppsed to use network_mode: "container:piavpn", when in separate docker-compose.yml files.
So, now it builds, and this is the traceback;
_**BTW, thanks for your help, this looks like really great software and I really want to get it working, but where I live there is basically no access to anything, so need to connect through a VPN.**_

[2021-03-12 13:18:54,419] NOOB - Loading fHDHR v0.9.0-beta with fHDHR_web v0.9.0-beta
[2021-03-12 13:18:54,434] WARNING - Do not run fHDHR with root privileges.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/app/main.py", line 30, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/app/fHDHR/cli/run.py", line 147, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
  File "/app/fHDHR/cli/run.py", line 120, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/app/fHDHR/cli/run.py", line 38, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
  File "/app/fHDHR/__init__.py", line 52, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
  File "/app/fHDHR/device/__init__.py", line 25, in __init__
    self.ssdp = SSDPServer(fhdhr)
  File "/app/fHDHR/device/ssdp/__init__.py", line 23, in __init__
    self.setup_ssdp()
  File "/app/fHDHR/device/ssdp/__init__.py", line 217, in setup_ssdp
    self.setup_multicasting()
  File "/app/fHDHR/device/ssdp/__init__.py", line 273, in setup_multicasting
    self.sock.setsockopt(
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 572, in setsockopt
    return self._sock.setsockopt(*args)
OSError: [Errno 19] No such device

**Comment by deathbybandaid** [comment]
Looks like it's failing to setup SSDP on port 1900.

I'll add some safer handling for this in a few minutes.

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/155

That may resolve your issue.

**Comment by wbilger** [comment]
Ok, getting somewhere now I think, but now cannot connect to port 5004, but it is going through the VPN, as you can see the plutoTV scan found 283 channels, where before it only found 11.

[2021-03-12 14:27:32,519] NOOB - Loading fHDHR v0.9.0-beta with fHDHR_web v0.9.0-beta
[2021-03-12 14:27:32,543] WARNING - Do not run fHDHR with root privileges.
[2021-03-12 14:27:37,142] ERROR - SSDP system will not be Initialized: [Errno 19] No such device
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/fHDHR_web/__init__.py", line 300, in run
    self.http.serve_forever()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 398, in serve_forever
    self.start()
  File "/usr/local/lib/python3.8/site-packages/gevent/baseserver.py", line 336, in start
    self.init_socket()
  File "/usr/local/lib/python3.8/site-packages/gevent/pywsgi.py", line 1545, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 180, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 192, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
  File "/usr/local/lib/python3.8/site-packages/gevent/server.py", line 288, in _tcp_listener
    sock.bind(address)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 563, in bind
    return self._sock.bind(address)
OSError: [Errno 99] Cannot assign requested address: ('192.168.1.10', 5004)
[2021-03-12 14:27:37,259] NOOB - Running Startup Tasks.
[2021-03-12 14:27:37,263] NOOB - Performing Channel Scan for plutotv. This Process can take some time, Please Wait.
[2021-03-12 14:28:33,985] NOOB - Updating plutotv EPG cache.
[2021-03-12 14:28:36,029] NOOB - Wrote plutotv EPG cache. 106408 Programs for 283 Channels
[2021-03-12 14:28:36,034] NOOB - Startup Tasks Complete.

**Comment by deathbybandaid** [comment]
depending on your OS, I'd suggest you see what's running on what ports.

Also, you can try using the config to change the fHDHR port to another port number

**Comment by deathbybandaid** [comment]
Doesn't solve your networking problem, but  https://github.com/fHDHR/fHDHR/pull/156 should at least be a little prettier for error handling.

**Comment by wbilger** [comment]
Nothing running on 5004, but I found it, and thanks that did cleanup the error handling.
In the config.ini I had to put the ipaddress back to 0.0.0.0 to use the vpn, as without the vpn I needed to set it to 192.168.1.10 to access the container. 
So far so good, now on to testing, thanks so much.
Also, FYI, in your Docs for docker it says to update to checkout master, when it should be main I think.

**Comment by deathbybandaid** [comment]
Glad that fixed it for you!
