### ISSUE TITLE
fHDHR_plugin_origin_IPTVorg fails

### ISSUE THREAD

**Issue by wbilger** [fHDHR/fHDHR#157]
Traceback Error from docker logs;

NOOB - Performing Channel Scan for iptvorg. This Process can take some time, Please Wait.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/app/main.py", line 30, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/app/fHDHR/cli/run.py", line 147, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
  File "/app/fHDHR/cli/run.py", line 120, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/app/fHDHR/cli/run.py", line 49, in run
    fhdhr.api.get("/api/startup_tasks")
  File "/app/fHDHR/api/__init__.py", line 104, in get
    self.client.get(url, headers=self.headers, *args)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1096,
  File "/app/fHDHR_web/api/startup_tasks.py", line 15, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/startup_tasks.py", line 32, in get
    self.fhdhr.api.get("%s&origin=%s" % (self.channel_update_url, origin))
  File "/app/fHDHR/api/__init__.py", line 104, in get
    self.client.get(url, headers=self.headers, *args)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1006, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.8/site-packages/flask/testing.py", line 222, in open
    return Client.open(
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.8/site-packages/werkzeug/test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/fHDHR_web/api/channels.py", line 20, in __call__
    return self.get(*args)
  File "/app/fHDHR_web/api/channels.py", line 164, in get
    self.fhdhr.device.channels.get_channels(forceupdate=True, origin=origin)
  File "/app/fHDHR/device/channels/__init__.py", line 229, in get_channels
    channel_dict_list = self.origins.origins_dict[origin].get_channels()
  File "/app/plugins/fHDHR_plugin_origin_IPTVorg/origin/__init__.py", line 60, in get_channels
    self.filtered_chan_json = self.filterlist()
  File "/app/plugins/fHDHR_plugin_origin_IPTVorg/origin/__init__.py", line 96, in filterlist
    if isinstance(channels_item[filter_key], list):
KeyError: 'country'

**Comment by deathbybandaid** [comment]
I'll look on Monday
