### ISSUE TITLE
Unable To Load fHDHR Web (ZeroDivisionError) 

### ISSUE THREAD

**Issue by DanTheTechMan** [fHDHR/fHDHR#165]
Hello,

I successfully got fHDHR set up on my NAS running Windows. It _appears_ to start fine, however whenever I try to load it in a web browser (either locally or remote), I get the following errors in the CMD window on my NAS:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 999,
 in handle_one_response
    self.run_application()
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 945,
 in run_application
    self.result = self.application(self.environ, self.start_response)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 2450, in
 wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1867, in
 handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\flask\_compat.py", line 39,
in reraise
    raise value
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 2447, in
 wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1952, in
 full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1821, in
 handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\flask\_compat.py", line 39,
in reraise
    raise value
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1950, in
 full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1936, in
 dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Temp\fHDHR\fHDHR_web\pages\index_html.py", line 14, in __call__
    return self.get(*args)
  File "C:\Temp\fHDHR\fHDHR_web\pages\index_html.py", line 37, in get
    fhdhr_status_dict["Channels"] = "%s from %s origins. Avg %s/origin" % (sum(c
hannel_counts), len(channel_counts), int(sum(channel_counts) / len(channel_count
s)))
ZeroDivisionError: division by zero
2021-03-26T23:35:38Z {'REMOTE_ADDR': '192.168.1.114', 'REMOTE_PORT': '41550', 'H
TTP_HOST': '192.168.1.150:5004', (hidden keys: 25)} failed with ZeroDivisionErro
r

[2021-03-26 19:35:38,830] INFO - 192.168.1.114 - - [2021-03-26 19:35:38] "GET /i
ndex HTTP/1.1" 500 161 0.046799

My primary use for this will be to stream Locast using Plex (I am coming from Locast2Plex, however that stopped working for me a few months ago so I went looking for an alternative. fHDHR looked very promising so I thought I would give it a try.) however I might want to expand beyond that in the future. Can anyone point me in the right direction on how to get it up and running?

**Comment by deathbybandaid** [comment]
Are you running the release version or the main branch? I thought I fixed this a couple months ago.

**Comment by DanTheTechMan** [comment]
The release version. Should I switch to the main branch?

**Comment by deathbybandaid** [comment]
I would try that if I were you, has many improvements

**Comment by DanTheTechMan** [comment]
Thanks. That worked. I just have one remaining question. How do I organize the plugins in the plugin folder so that fHDHR will recognize them? Do I just dump all of the the plugins in the plugins folder as is or do I have subfolders for each plugin? If I create subfolders what do I name them?

**Comment by deathbybandaid** [comment]
Easiest way is to go to your plugin folder, and git clone the plugin repos

**Comment by DanTheTechMan** [comment]
I figured that, but using git is not an option for me (I'm running Windows). Whenever I download a repo from GitHub, I always have to download it as a ZIP file. That't why I asked how to structure the plugins folder.

**Comment by warrentc3** [comment]
> I figured that, but using git is not an option for me (I'm running Windows). Whenever I download a repo from GitHub, I always have to download it as a ZIP file. That't why I asked how to structure the plugins folder.

Git is on Windows too.  What you're saying is you don't know how... not that it isn't an option.

**Comment by DanTheTechMan** [comment]
I already knew it was an option on Windows, just not Out Of The Box. I'm running fHDHR on a NAS with a rather small Windows partition (~60GB) and that partition size cannot be changed (as it stands now I only have ~9GB free), so I'm trying to keep the 3rd party software installed on the NAS to a minimum.

On a side note I did find the GitHub CLI tool which looks perfect for me (small footprint and nothing "extra" added to my system), so I'm going to try that out now.

**Comment by deathbybandaid** [comment]
Downloading and extracting the zip should* work fine. As long as the entirety of the plugin is in a folder with the layout of the repo as the contents

**Comment by DanTheTechMan** [comment]
Thanks. I got it up and running and able to recognize the plugins (I installed the GitHub CLI tool and Git for Windows). Now I'm running into another issue and that is getting Plex to recognize the tuner. For whatever reason whenever I try to run SSDP from the web module it brings up the following error (which I have a feeling is why Plex can't recognize the tuner):

[2021-03-28 11:28:39,658] INFO - 192.168.1.114 - - [2021-03-28 11:28:39] "GET /a
pi/ssdp?method=scan&redirect=/ssdp HTTP/1.1" 500 161 0.265193
[2021-03-28 11:28:42,434] INFO - 192.168.1.114 - - [2021-03-28 11:28:42] "GET /s
sdp HTTP/1.1" 200 4850 0.046799
[2021-03-28 11:28:43,979] INFO - Sending Alive message to network.
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 999,
 in handle_one_response
    self.run_application()
  File "C:\Program Files\Python38\lib\site-packages\gevent\pywsgi.py", line 945,
 in run_application
    self.result = self.application(self.environ, self.start_response)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 2450, in
 wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1867, in
 handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\flask\_compat.py", line 39,
in reraise
    raise value
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 2447, in
 wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1952, in
 full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1821, in
 handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\flask\_compat.py", line 39,
in reraise
    raise value
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1950, in
 full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python38\lib\site-packages\flask\app.py", line 1936, in
 dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Temp\fHDHR\fHDHR_web\api\ssdp.py", line 17, in __call__
    return self.get(*args)
  File "C:\Temp\fHDHR\fHDHR_web\api\ssdp.py", line 28, in get
    self.fhdhr.device.ssdp.do_alive()
  File "C:\Temp\fHDHR\fHDHR\device\ssdp\__init__.py", line 98, in do_alive
    self.do_notify(self.broadcast_address_tuple)
AttributeError: 'SSDPServer' object has no attribute 'broadcast_address_tuple'
2021-03-28T15:28:44Z {'REMOTE_ADDR': '192.168.1.114', 'REMOTE_PORT': '10185', 'H
TTP_HOST': '192.168.1.150:5004', (hidden keys: 26)} failed with AttributeError

Is there any way to rectify this?

Thanks for all your help so far!

**Comment by deathbybandaid** [comment]
Do you have the hdhr plugin added? If so, you can manually add the link given by the hdhr tab in the webui (more reliable anyway)

**Comment by DanTheTechMan** [comment]
No, I do not. Thank you for that recommendation. I'll install it now.

**Comment by DanTheTechMan** [comment]
I was successfully able to get the virtual tuner added to Plex and Plex is building the guide as I type this. My last point of concern is if I will successfully be able to stream any or all of the channels (the exact issue I had with Locast2Plex which is part of the reason why I've moved on). Fingers (and toes) crossed!

**Comment by DanTheTechMan** [comment]
I successfully have it up and running. Thank you so much for all your help!
