### ISSUE TITLE
fHDHR stopped working

### ISSUE THREAD

**Issue by CHJ85** [fHDHR/fHDHR#183]
Hi there. fHDHR worked at first, and now I'm getting these errors.
Here's the output. To me, this is like reading Greek, so could you please help me figure out what the issue is?
Thank you.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/chris/fHDHR/fHDHR_web/api/tuners.py", line 20, in __call__
    return self.get(*args)
  File "/home/chris/fHDHR/fHDHR_web/api/tuners.py", line 148, in get
    stream_args = self.fhdhr.device.tuners.get_stream_info(stream_args)
  File "/home/chris/fHDHR/fHDHR/device/tuners/__init__.py", line 149, in get_stream_info
    stream_info = self.channels.get_channel_stream(stream_args, stream_args["origin"])
  File "/home/chris/fHDHR/fHDHR/device/channels/__init__.py", line 197, in get_channel_stream
    return self.origins.origins_dict[origin].get_channel_stream(self.get_channel_dict("number", stream_args["channel"]), stream_args)
  File "/home/chris/fHDHR/plugins/fHDHR_plugin_origin_XUMO-main/origin/__init__.py", line 94, in get_channel_stream
    stream_id_info_json = self.plugin_utils.web.session.get(stream_id_info_url).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-09-13T01:56:57Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '49850', 'HTTP_HOST': '0.0.0.0:5004', (hidden keys: 23)} failed with JSONDecodeError

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.9/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/chris/fHDHR/fHDHR_web/api/tuners.py", line 20, in __call__
    return self.get(*args)
  File "/home/chris/fHDHR/fHDHR_web/api/tuners.py", line 148, in get
    stream_args = self.fhdhr.device.tuners.get_stream_info(stream_args)
  File "/home/chris/fHDHR/fHDHR/device/tuners/__init__.py", line 149, in get_stream_info
    stream_info = self.channels.get_channel_stream(stream_args, stream_args["origin"])
  File "/home/chris/fHDHR/fHDHR/device/channels/__init__.py", line 197, in get_channel_stream
    return self.origins.origins_dict[origin].get_channel_stream(self.get_channel_dict("number", stream_args["channel"]), stream_args)
  File "/home/chris/fHDHR/plugins/fHDHR_plugin_origin_XUMO-main/origin/__init__.py", line 94, in get_channel_stream
    stream_id_info_json = self.plugin_utils.web.session.get(stream_id_info_url).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-09-13T01:56:57Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '49852', 'HTTP_HOST': '0.0.0.0:5004', (hidden keys: 20)} failed with JSONDecodeError
```

**Comment by deathbybandaid** [comment]
This is an issue with the xumo plugin
