### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR#291]
Hi,

FYI, with the latest updates (bunch of them today 😄). I get the error below. BTW, I did update to the latest for fHDHR, and the ceton origin plugin. Thinking that's all that is needed?

```
[2022-03-01 17:45:28,611] INFO - Detecting and Opening any found EPG plugins.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/mnt/ProgSSD/fHDHR/main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 174, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 133, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 40, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/__init__.py", line 64, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/__init__.py", line 23, in __init__
    self.epg = EPG(fhdhr, self.channels, origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/epg/__init__.py", line 28, in __init__
    frequency_seconds = self.epg_handling[epg_method].update_frequency
AttributeError: 'blocksEPG' object has no attribute 'update_frequency'
```

Thanks!

**Comment by deathbybandaid** [comment]
Try https://github.com/fHDHR/fHDHR/pull/292

**Comment by deathbybandaid** [comment]
I put wrapper classes around SSDP, Origin, and EPG plugins to standardize some things

**Comment by arrmo** [comment]
Gotcha! Tried it, 
```
[2022-03-01 18:30:18,771] INFO - Detecting and Opening any found EPG plugins.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/mnt/ProgSSD/fHDHR/main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 174, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 133, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 40, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/__init__.py", line 64, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/__init__.py", line 23, in __init__
    self.epg = EPG(fhdhr, self.channels, origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/epg/__init__.py", line 28, in __init__
    frequency_seconds = self.epg_handling[epg_method].update_frequency
AttributeError: 'blocksEPG' object has no attribute 'update_frequency'
```

**Comment by arrmo** [comment]
Just a sec - I think it's the changes I had in place for detection, etc. May have to redo those after the changes 😞

**Comment by arrmo** [comment]
Nope, the error above still happens - just more errors also, when I try to stream with my changes.

**Comment by deathbybandaid** [comment]
Try with https://github.com/fHDHR/fHDHR/pull/293

I might just be tired, but I see no code that should be making blocks show in the list of EPG like that

**Comment by deathbybandaid** [comment]
wait, maybe I do

**Comment by deathbybandaid** [comment]
It's for when an origin doesn't provide it's own EPG

**Comment by deathbybandaid** [comment]
try with

https://github.com/fHDHR/fHDHR/pull/294

**Comment by arrmo** [comment]
Nope, log here,
```
[2022-03-01 18:56:00,077] INFO - Detecting and Opening any found EPG plugins.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/mnt/ProgSSD/fHDHR/main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 174, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 133, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/cli/run.py", line 40, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
  File "/mnt/ProgSSD/fHDHR/fHDHR/__init__.py", line 64, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/__init__.py", line 23, in __init__
    self.epg = EPG(fhdhr, self.channels, origins)
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/epg/__init__.py", line 28, in __init__
    frequency_seconds = self.epg_handling[epg_method].update_frequency
  File "/mnt/ProgSSD/fHDHR/fHDHR/device/epg/blocks.py", line 174, in update_frequency
    return self.config_dict["epg_update_frequency"]
KeyError: 'epg_update_frequency'
```

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/295

**Comment by arrmo** [comment]
Yep! Thanks! Have a nice evening.

**Comment by deathbybandaid** [comment]
So close it?
