### ISSUE TITLE
Missing Python Module

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#323]
You need to include pytz in your required list of modules to install. One of the plugins won't run without it.

**Comment by deathbybandaid** [comment]
Which plugin? The requirements for core does not align with plugins, so the requirement goes to the plugin repo

**Comment by Protektor-Desura** [comment]
No idea but here is the log for your docker.

[2022-07-13 07:58:48,391] WARNING - Do not run fHDHR with root privileges.
[2022-07-13 07:58:48,392] NOOB - Loading  fHDHR v0.9.3-beta, fHDHR_web v0.9.2-beta
[2022-07-13 07:58:48,392] INFO - Importing Core config values from Configuration File: /app/config/config.ini
[2022-07-13 07:58:48,395] INFO - Importing Plugin values from Configuration File: /app/config/config.ini
[2022-07-13 07:58:48,397] INFO - Setting Up sqlite database
[2022-07-13 07:58:48,412] INFO - Scanning for plugins: /app/plugins
[2022-07-13 07:58:48,413] INFO - Found origin type plugin: STIRR v0.6.0-beta. 
[2022-07-13 07:58:48,414] INFO - Checking For STIRR Plugin Requirements file.
[2022-07-13 07:58:48,414] INFO - Installing STIRR Plugin Requirements from /app/plugins/fHDHR_plugin_origin_STIRR/requirements.txt
[2022-07-13 07:58:48,415] INFO - Found alt_stream type plugin: ffmpeg v0.7.0-beta. 
[2022-07-13 07:58:48,415] INFO - Checking For ffmpeg Plugin Requirements file.
[2022-07-13 07:58:48,416] INFO - Installing ffmpeg Plugin Requirements from /app/plugins/fHDHR_plugin_stream_ffmpeg/requirements.txt
[2022-07-13 07:58:48,416] INFO - Found alt_epg type plugin: tvtv v0.6.0-beta. 
[2022-07-13 07:58:48,417] INFO - Checking For tvtv Plugin Requirements file.
[2022-07-13 07:58:48,417] INFO - Installing tvtv Plugin Requirements from /app/plugins/fHDHR_plugin_epg_tvtv/requirements.txt
[2022-07-13 07:58:48,418] INFO - Found origin type plugin: IPTVorg v0.6.0-beta. 
[2022-07-13 07:58:48,418] INFO - Checking For IPTVorg Plugin Requirements file.
[2022-07-13 07:58:48,419] INFO - Installing IPTVorg Plugin Requirements from /app/plugins/fHDHR_plugin_origin_IPTVorg/requirements.txt
[2022-07-13 07:58:48,421] INFO - Found origin type plugin: XUMO v0.6.0-beta. 
[2022-07-13 07:58:48,422] INFO - Checking For XUMO Plugin Requirements file.
[2022-07-13 07:58:48,423] INFO - Installing XUMO Plugin Requirements from /app/plugins/fHDHR_plugin_origin_XUMO/requirements.txt
[2022-07-13 07:58:48,424] INFO - Found origin type plugin: USTVGO v0.6.0-beta. 
[2022-07-13 07:58:48,424] INFO - Checking For USTVGO Plugin Requirements file.
[2022-07-13 07:58:48,424] INFO - Installing USTVGO Plugin Requirements from /app/plugins/fHDHR_plugin_origin_USTVGO/requirements.txt
[2022-07-13 07:58:48,425] INFO - Found interface type plugin: HDHR v0.6.0-beta. 
[2022-07-13 07:58:48,426] INFO - Checking For HDHR Plugin Requirements file.
[2022-07-13 07:58:48,426] INFO - Installing HDHR Plugin Requirements from /app/plugins/fHDHR_plugin_interface_hdhr/requirements.txt
[2022-07-13 07:58:48,427] INFO - Found alt_epg type plugin: zap2it v0.6.0-beta. 
[2022-07-13 07:58:48,427] INFO - Checking For zap2it Plugin Requirements file.
[2022-07-13 07:58:48,428] INFO - Installing zap2it Plugin Requirements from /app/plugins/fHDHR_plugin_epg_zap2it/requirements.txt
[2022-07-13 07:58:48,428] INFO - Found origin type plugin: NewsOn v0.6.0-beta. 
[2022-07-13 07:58:48,429] INFO - Checking For NewsOn Plugin Requirements file.
[2022-07-13 07:58:48,429] INFO - Installing NewsOn Plugin Requirements from /app/plugins/fHDHR_plugin_origin_NewsOn/requirements.txt
[2022-07-13 07:58:48,430] INFO - Found origin type plugin: ToonamiAftermath v0.6.0-beta. 
[2022-07-13 07:58:48,430] INFO - Checking For ToonamiAftermath Plugin Requirements file.
[2022-07-13 07:58:48,431] INFO - Installing ToonamiAftermath Plugin Requirements from /app/plugins/fHDHR_plugin_origin_ToonamiAftermath/requirements.txt
[2022-07-13 07:58:48,432] INFO - Found origin type plugin: PlutoTV v0.6.0-beta. 
[2022-07-13 07:58:48,432] INFO - Checking For PlutoTV Plugin Requirements file.
[2022-07-13 07:58:48,432] INFO - Installing PlutoTV Plugin Requirements from /app/plugins/fHDHR_plugin_origin_plutotv/requirements.txt
[2022-07-13 07:58:48,433] INFO - Loading plugins.
Checking and Installing Core Dependencies.
Traceback (most recent call last):
  File "/app/main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/app/fHDHR/cli/run.py", line 180, in main
    returned_code = start(args, script_dir, fhdhr_time, fHDHR_web, deps)
  File "/app/fHDHR/cli/run.py", line 135, in start
    plugins = fHDHR.plugins.PluginsHandler(settings, logger, db, versions, deps)
  File "/app/fHDHR/plugins/__init__.py", line 27, in __init__
    self.load_plugins()
  File "/app/fHDHR/plugins/__init__.py", line 136, in load_plugins
    plugin_item = Plugin(self.config, self.logger, self.db, self.versions, plugin_name, plugin_path, plugin_conf, plugin_manifest)
  File "/app/fHDHR/plugins/plugin.py", line 37, in __init__
    self._module = self._load()
  File "/app/fHDHR/plugins/plugin.py", line 77, in _load
    mod = imp.load_module(self.plugin_dict_name, None, self.path, description)
  File "/usr/local/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/local/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/plugins/fHDHR_plugin_origin_ToonamiAftermath/epg/__init__.py", line 2, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

**Comment by deathbybandaid** [comment]
I'm not a docker person, so not sure how to help with that. Maybe start a seperate issue for that

**Comment by Protektor-Desura** [comment]
This shows the problem is the https://github.com/fHDHR/fHDHR_plugin_origin_ToonamiAftermath/requirements.txt

file is empty. It should have "pytz" in it. Shouldn't it?

**Comment by Protektor-Desura** [comment]
I'm pretty sure that is the case because if I that to my local copy of the plugin then everything works perfectly.

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_origin_ToonamiAftermath/blob/main/requirements.txt

I added the req
