### ISSUE TITLE
New install generates error for IPTVOrg

### ISSUE THREAD

**Issue by CTJohnK** [fHDHR/fHDHR#334]
Getting the following error message when staring up a fresh install of fHDHR with the 'hdhr' and 'IPTVorg' plugins installed.  Any ideas?

"[2023-04-03 13:16:17,067] NOOB - Performing Channel Scan for iptvorg. This Process can take some time, Please Wait.
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "/home/john/fHDHR-IPTV/fHDHR/cli/run.py", line 180, in main
    returned_code = start(args, script_dir, fhdhr_time, fHDHR_web, deps)
  File "/home/john/fHDHR-IPTV/fHDHR/cli/run.py", line 137, in start
    return run(settings, fhdhr_time, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
  File "/home/john/fHDHR-IPTV/fHDHR/cli/run.py", line 63, in run
    fhdhr.scheduler.startup_tasks()
  File "/home/john/fHDHR-IPTV/fHDHR/scheduler/__init__.py", line 193, in startup_tasks
    self.startup_channel_scan(tags_list)
  File "/home/john/fHDHR-IPTV/fHDHR/scheduler/__init__.py", line 215, in startup_channel_scan
    self.fhdhr.scheduler.run_from_tag("%s Channel Scan" % origin_name)
  File "/home/john/fHDHR-IPTV/fHDHR/scheduler/__init__.py", line 170, in run_from_tag
    job_item.run()
  File "/home/john/.local/lib/python3.8/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/home/john/fHDHR-IPTV/fHDHR/scheduler/__init__.py", line 89, in wrapper
    result = func(*args, **kwargs)
  File "/home/john/fHDHR-IPTV/fHDHR/origins/channels/__init__.py", line 140, in scan_channels
    channel_dict_list = self.origin_obj.get_channels()
  File "/home/john/fHDHR-IPTV/fHDHR/origins/origin.py", line 144, in get_channels
    return self.method.get_channels()
  File "/home/john/fHDHR-IPTV/plugins/fHDHR_plugin_origin_IPTVorg/origin/__init__.py", line 49, in get_channels
    self.unfiltered_chan_json = self.get_unfiltered_chan_json()
  File "/home/john/fHDHR-IPTV/plugins/fHDHR_plugin_origin_IPTVorg/origin/__init__.py", line 75, in get_unfiltered_chan_json
    return urlopn.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"

**Comment by deathbybandaid** [comment]
Unfortunately, the origin plugins are notoriously difficult to maintain, as I don't use them personally, and the methodology needed to use them constantly changes.

I wrote fHDHR as a hobby project, with hopes the community would step up and help maintain plugins. This never came to fruition, and my life became very busy.

**Comment by DanAustinGH** [comment]
You might try without the iptvorg plugin, the log is clear that the channel list related to that plugin is not in the expected format.

**Comment by DanAustinGH** [comment]
And while I do not use the plugin, it was an easy check and it is clear that there are changes on the iptv-org site that broke the channel list fetch, and the new method is not obvious.

**Comment by CTJohnK** [comment]
@deathbybandaid Understood, life happens.
@DanAustinGH Yes, it starts without the IPTV plugin, but I wanted to see what I might get for channels.

I was letting you and anyone else who might be tinkering of the error.  I'm not a Python person, so I'm trying to learn it.

With that said, as a side note, I also found a couple of hiccups in the PlutoTV plugin, specifically with generating the XMLTV data.  One was the use of 'None' for the time zone offset, so I changed my version to pull from the config.ini file.  The other related to the episode number, some of the program data coming back had 'Unknown' which didn't convert to an integer.  I added an IF/ELSE to get around that.

Now I have the PlutoTV plugin working with Jellyfin and Plex.

**Comment by kghorvath** [comment]
> @deathbybandaid Understood, life happens.
> 
> @DanAustinGH Yes, it starts without the IPTV plugin, but I wanted to see what I might get for channels.
> 
> 
> 
> I was letting you and anyone else who might be tinkering of the error.  I'm not a Python person, so I'm trying to learn it.
> 
> 
> 
> With that said, as a side note, I also found a couple of hiccups in the PlutoTV plugin, specifically with generating the XMLTV data.  One was the use of 'None' for the time zone offset, so I changed my version to pull from the config.ini file.  The other related to the episode number, some of the program data coming back had 'Unknown' which didn't convert to an integer.  I added an IF/ELSE to get around that.
> 
> 
> 
> Now I have the PlutoTV plugin working with Jellyfin and Plex.

Hey I know it's been a few years but I was wondering if you remember exactly what you modified to fix this? I'm running into what I believe is the same issue trying to generate XMLTB with the PlutoTV plugin.
