### ISSUE TITLE
EPG error on Windows

### ISSUE THREAD

**Issue by tharris9d** [fHDHR/fHDHR#56]
I setup a new build with the newest fHDHR system on Windows with the plugins. I am getting an invalid epg error. Am I missing a plugin? I have the origin locast plugin in the plugin folder. I also have the cluster and hdhr interface plugins. I have the following epg section in the config.ini. See the error below...
[epg]
images = pass
method = origin
update_frequency = 43200
reverse_days = -1
forward_days = 7
block_size = 1800
xmltv_offset = +0000

Loading fHDHR_web v0.8.1-beta
Found interface type plugin: HDHR v0.6.0-beta.
Found origin type plugin: Locast v0.6.0-beta.
Loading Configuration File: c:\code\fhdhr_locast_2\config.ini
Traceback (most recent call last):
  File "C:\code\fhdhr_locast_2\main.py", line 16, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web))
  File "C:\code\fhdhr_locast_2\fHDHR\cli\run.py", line 108, in main
    returned_code = start(args, script_dir, fHDHR_web)
  File "C:\code\fhdhr_locast_2\fHDHR\cli\run.py", line 94, in start
    settings.config_verification_plugins()
  File "C:\code\fhdhr_locast_2\fHDHR\config\__init__.py", line 152, in config_verification_plugins
    raise fHDHR.exceptions.ConfigurationError("Invalid EPG Method. Exiting...")
fHDHR.exceptions.ConfigurationError: ConfigurationError: Invalid EPG Method. Exiting...
Press any key to continue . . .

**Comment by deathbybandaid** [comment]
change your method from "origin" to "locast"

**Comment by deathbybandaid** [comment]
I'll add some extra handling for this

**Comment by deathbybandaid** [comment]
actually, I can make "origin" work

**Comment by deathbybandaid** [comment]
@tharris9d https://github.com/fHDHR/fHDHR/pull/57

That adds "origin" and "origins" as a valid config option.

Thanks for finding this issue

**Comment by deathbybandaid** [comment]
@tharris9d is this fixed for you?

**Comment by tharris9d** [comment]
@deathbybandaid Sorry it took so long to get back to this. Yes EPG is now working. I tested the latest version (2-17)and I am getting new errors. Have there been changes to the config? I will test for awhile and post what I find.

**Comment by deathbybandaid** [comment]
can you show what errors you're getting? you gave me nothing to troubleshoot....

**Comment by deathbybandaid** [comment]
if your error is 

````
ModuleNotFoundError: No module named 'schedule'
````

then run `pip3 install -r requirements.txt`

Always remember to update your requirements when you see a message like that

**Comment by tharris9d** [comment]
I ran the requirements update after updating the the latest codebase and plugins. I am using the HDHR and origin locast plugins only. 
This is what I get. My config.ini looks good based on the docs.
[2021-02-17 11:43:35,777] NOOB - Loading fHDHR v0.9.0-beta with fHDHR_web v0.9.0-beta
[2021-02-17 11:43:43,009] NOOB - Running Startup Tasks.
[2021-02-17 11:43:43,009] NOOB - Startup Tasks Complete.
Traceback (most recent call last):
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gevent\pywsgi.py", line 970, in handle_one_response
    self.run_application()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gevent\pywsgi.py", line 917, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Valued Customer\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\code\fhdhr_locast_1\fHDHR_web\pages\index_html.py", line 14, in __call__
    return self.get(*args)
  File "C:\code\fhdhr_locast_1\fHDHR_web\pages\index_html.py", line 37, in get
    fhdhr_status_dict["Channels"] = "%s from %s origins. Avg %s/origin" % (sum(channel_counts), len(channel_counts), int(sum(channel_counts) / len(channel_counts)))
ZeroDivisionError: division by zero
2021-02-17T19:44:36Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '57556', 'HTTP_HOST': '127.0.0.1:5006', (hidden keys: 33)} failed with ZeroDivisionError

**Comment by deathbybandaid** [comment]
Try going to the /channels page and forcing an update

**Comment by tharris9d** [comment]
I re-copied the plugins to make sure I got the new versions.
This is the error I get now.

  "  self.setup_discovery()
  File "C:\code\fhdhr_locast_1\plugins\fHDHR_plugin_interface_hdhr-main\interface\discovery_udp.py", line 64, in setup_discovery
    self.sock.bind(('0.0.0.0', HDHOMERUN_DISCOVER_UDP_PORT))
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions"

**Comment by tharris9d** [comment]
The interface won't open do force an update. Do I need to open up a port on the firewall? possibly a config.ini issue?

**Comment by deathbybandaid** [comment]
Update both core, and the hdhr plugin, I've pushed handling for both

**Comment by tharris9d** [comment]
Updating now.

**Comment by tharris9d** [comment]
Your update fixed the issue. Channels loaded, Guide works, Shows play fine when clicking Play (Through VLC). I will do some further testing of the recording and playback in Plex. Thanks for the support. I think you can close this ticket now.
